import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "./humMenu.css";

import { SessionProvider } from "next-auth/react";
import Layout from "@/layout/Layout";
import BackStyle3 from "@/ui/BackStyle3";
import { ViewTransitions } from "next-view-transitions";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SessionProvider>
                      <ViewTransitions>
              <Layout>
           <BackStyle3>
                {children}
           </BackStyle3>
              </Layout>

                      </ViewTransitions>
        </SessionProvider>
      </body>
    </html>
  );
}
